{
 "title": "stack health",
 "time": { "from": "now-5m", "to": "now" },
 "panels": [
  {
   "title": "Stack Alerts",
   "type": "alertlist",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 0 },
   "targets": [
    { "expr": "agent_", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "scrape targets health",
   "type": "stat",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "dateTimeFromNow" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "timestamp(max(scrape_duration_seconds{}) by (k8s_container_name)) * 1000",
     "legendFormat": "{{ k8s_container_name }}"
    }
   ]
  },
  {
   "title": "Grafana errors",
   "type": "logs",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "{vector_instance=\"vector-dd64548c9-9d74t\"} | logfmt | line_format \"{{ .message }}\" | logfmt | level=`error`"
    }
   ]
  },
  {
   "title": "Total Prometheus Series",
   "type": "stat",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 7 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "prometheus_tsdb_head_series", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Loki ingester streams",
   "type": "stat",
   "gridPos": { "h": 6, "w": 6, "x": 6, "y": 7 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(loki_ingester_streams_created_total)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "vector event throughput",
   "type": "bargauge",
   "gridPos": { "h": 6, "w": 6, "x": 12, "y": 7 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(vector_events_in_total[1m]))",
     "legendFormat": "in"
    },
    {
     "expr": "sum(increase(vector_events_out_total[1m]))",
     "legendFormat": "out"
    }
   ]
  },
  {
   "title": "Grafana agent logs sent",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 6, "x": 18, "y": 7 },
   "targets": [
    {
     "expr": "rate(promtail_sent_entries_total{}[5m])",
     "legendFormat": "n logs"
    }
   ]
  }
 ]
}