---
apiVersion: builtin
kind: PatchTransformer
metadata:
  name: loki-metadata-patch
patch: '[{"op": "replace", "path": "/spec/template/metadata/annotations/prometheus.io.service.port", "value": "3100"}]'
target:
  name: loki
  kind: Deployment
---
apiVersion: builtin
kind: PatchTransformer
metadata:
  name: grafana-metadata-patch
patch: '[{"op": "replace", "path": "/spec/template/metadata/annotations/prometheus.io.service.port", "value": "3000"}]'
target:
  name: grafana
  kind: Deployment