---
apiVersion: v1
kind: Service
metadata:
  name: grafana-db
spec:
  ports:
    - port: 3306
      protocol: TCP
      targetPort: mysql
  selector:
    app: grafana-db
  sessionAffinity: None
  type: LoadBalancer