---
# Source: loki/templates/service-headless.yaml
apiVersion: v1
kind: Service
metadata:
  name: loki
spec:
  # clusterIP: None
  ports:
    - port: 3100
      protocol: TCP
      name: http
      targetPort: http
  selector:
    app: loki
  # type: LoadBalancer