---
apiVersion: v1
kind: Service
metadata:
  labels:
    name: vector
  name: vector
spec:
  type: LoadBalancer
  ports:
  - name: vector-api
    port: 8080
    targetPort: 8080
  - name: syslog-tcp
    port: 601
    targetPort: 6601
    protocol: TCP
  - name: syslog-udp
    port: 514
    targetPort: 5514
    protocol: UDP
  selector:
    name: vector