---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: grafana-db
  name: grafana-db
spec:
  selector:
    matchLabels:
      app: grafana-db
  template:
    metadata:
      labels:
        app: grafana-db
    spec:
      containers:
      - name: grafana-db
        image: mysql:8
        imagePullPolicy: IfNotPresent
        env:
        - name: MYSQL_RANDOM_ROOT_PASSWORD
          value: 'true'
        - name: MYSQL_DATABASE
          value: grafana
        - name: MYSQL_USER
          valueFrom:
            secretKeyRef:
              name: grafana-db-grafana-credentials
              key: username
        - name: MYSQL_PASSWORD
          valueFrom:
            secretKeyRef:
              name: grafana-db-grafana-credentials
              key: password
        resources:
          limits:
            memory: "2000M"
            cpu: "1"
        ports:
        - containerPort: 3306
          name: mysql
        volumeMounts:
          - mountPath: /var/lib/mysql 
            name: mysql-data
          - mountPath: /docker-entrypoint-initdb.d
            name: grafana-db-config-volume
      volumes:
        - name: mysql-data
          persistentVolumeClaim:
            claimName: mysql-pvc
        - name: grafana-db-config-volume
          configMap:
            name: grafana-db-config
