---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: loki
  name: loki
spec:
  selector:
    matchLabels:
      app: loki
  template:
    metadata:
      labels:
        app: loki
      annotations:
        prometheus.io.service.port: "3100"
    spec:
      securityContext:
        fsGroup: 472
      containers:
        - name: loki
          image: grafana/loki:2.4.2
          imagePullPolicy: IfNotPresent
          args:
              - "-config.file=/etc/loki/loki.yaml"
          resources:
            limits:
              memory: "3000M"
              cpu: "1"
          ports:
          - containerPort: 3100
            name: http
            protocol: TCP
          volumeMounts:
            - mountPath: /etc/loki
              name: loki-config-volume
            - mountPath: /var/loki
              name: loki-data
            - mountPath: /var/loki/index
              name: loki-index
          livenessProbe:
            httpGet:
              path: /ready
              port: http
            initialDelaySeconds: 45
          readinessProbe:
            httpGet:
              path: /ready
              port: http
            initialDelaySeconds: 45
      volumes:
        - name: loki-index
          persistentVolumeClaim:
            claimName: loki-index-pvc
        - name: loki-data
          persistentVolumeClaim:
            claimName: loki-data-pvc
        - name: loki-config-volume
          configMap:
            name: loki-config
