---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: prometheus-k8s-sd
rules:
- apiGroups:
  - ""
  resources:
  - services
  - endpoints
  - pods
  - pods/log
  verbs:
  - get
  - list
  - watch
